#!/bin/bash
dayFile="Day0"
programDayFile="ProgramDay0"
dayTestFile="Day0KtTest"
year="2023"

testKotlin="../src/test/kotlin/adventofcode${year}"
resources="../src/main/resources/adventofcode${year}"
kotlin="../src/main/kotlin/adventofcode${year}"

mkdir -p $testKotlin
mkdir -p $resources
mkdir -p $kotlin

counter=1
while ((counter!=26))
do
  echo "---- Init day${counter} ----"
  echo "Create ${resources}/day${counter}.txt"
  touch "${resources}/day${counter}.txt"
  ./createSource $year $counter $kotlin $dayFile
  ./createSource $year $counter $kotlin $programDayFile
  ./createSource $year $counter $testKotlin $dayTestFile
	((counter+=1))
done
exit 0
